# Generated by Django 5.2.5 on 2025-10-26 00:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título corto de la notificación', max_length=200)),
                ('mensaje', models.TextField(help_text='Mensaje detallado de la notificación')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error')], default='info', help_text='Tipo de notificación (afecta el color/icono)', max_length=10)),
                ('url', models.CharField(blank=True, help_text='URL a la que redirigir cuando se hace clic', max_length=500, null=True)),
                ('leida', models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída')),
                ('datos_extra', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación de la notificación')),
                ('fecha_leida', models.DateTimeField(blank=True, help_text='Fecha en que se leyó la notificación', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario destinatario de la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_creacion'], name='notificacio_usuario_b76847_idx'), models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_2c9179_idx')],
            },
        ),
    ]
