# Generated by Django 5.2.5 on 2025-12-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_remove_notificacion_notificacio_usuario_b76847_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='fecha_leida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='importante',
            field=models.BooleanField(default=False),
        ),
    ]
