# Generated by Django 5.2.5 on 2025-10-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilempleado',
            name='departamento',
        ),
    ]
