# Generated by Django 5.2.5 on 2025-10-06 22:47

from django.db import migrations, models


def asignar_ruts_temporales(apps, schema_editor):
    """Asigna RUTs temporales únicos a usuarios existentes"""
    PerfilEmpleado = apps.get_model('home', 'PerfilEmpleado')
    
    for index, perfil in enumerate(PerfilEmpleado.objects.all(), start=1):
        # Generar RUT temporal único: 11111111-1, 22222222-2, etc.
        numero = str(index).zfill(8)
        digito = str(index % 10)
        rut_temporal = f"{numero[0]}.{numero[1:4]}.{numero[4:7]}-{digito}"
        perfil.rut = rut_temporal
        perfil.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_perfilempleado_departamento'),
    ]

    operations = [
        # Primero agregar el campo sin unique y con null=True
        migrations.AddField(
            model_name='perfilempleado',
            name='rut',
            field=models.CharField(
                help_text='Formato: 12.345.678-9', 
                max_length=12, 
                null=True,
                blank=True,
                verbose_name='RUT'
            ),
        ),
        # Ejecutar función para asignar RUTs temporales
        migrations.RunPython(asignar_ruts_temporales, migrations.RunPython.noop),
        # Ahora hacer el campo unique y no nulo
        migrations.AlterField(
            model_name='perfilempleado',
            name='rut',
            field=models.CharField(
                help_text='Formato: 12.345.678-9',
                max_length=12,
                unique=True,
                verbose_name='RUT'
            ),
        ),
    ]