# Generated by Django 5.2.5 on 2025-10-06 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_perfilempleado_rut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='light', max_length=10, verbose_name='Tema')),
                ('tamano_fuente', models.CharField(choices=[('small', 'Pequeño'), ('medium', 'Mediano'), ('large', 'Grande')], default='medium', max_length=10, verbose_name='Tamaño de Fuente')),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5, verbose_name='Idioma')),
                ('notificaciones_email', models.BooleanField(default=True, verbose_name='Recibir notificaciones por email')),
                ('notificaciones_sistema', models.BooleanField(default=True, verbose_name='Mostrar notificaciones en el sistema')),
                ('herramienta_calculadora', models.BooleanField(default=True, verbose_name='Calculadora')),
                ('herramienta_notas', models.BooleanField(default=True, verbose_name='Bloc de Notas')),
                ('herramienta_recordatorios', models.BooleanField(default=True, verbose_name='Recordatorios')),
                ('herramienta_conversor', models.BooleanField(default=True, verbose_name='Conversor de Unidades')),
                ('mostrar_tutorial', models.BooleanField(default=True, verbose_name='Mostrar tutorial inicial')),
                ('compactar_sidebar', models.BooleanField(default=False, verbose_name='Sidebar compacta por defecto')),
                ('items_por_pagina', models.IntegerField(default=15, verbose_name='Items por página')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuarios',
            },
        ),
    ]
