# Generated by Django 5.2.6 on 2026-03-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_configuracionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempleado',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Token Push Notificaciones'),
        ),
    ]
