# Generated by Django 5.2.5 on 2025-09-20 21:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de Empleado',
                'verbose_name_plural': 'Categorías de Empleados',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='cotizaciones.categoriaempleado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_trabajo', to='home.perfilempleado')),
            ],
            options={
                'verbose_name': 'Empleado-Categoría',
                'verbose_name_plural': 'Empleados-Categorías',
                'unique_together': {('empleado', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='ItemManoObraEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('horas_asignadas', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_asignados', to='home.perfilempleado')),
                ('item_mano_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_asignados', to='cotizaciones.itemmanoobra')),
            ],
            options={
                'verbose_name': 'Empleado Asignado',
                'verbose_name_plural': 'Empleados Asignados',
                'unique_together': {('item_mano_obra', 'empleado')},
            },
        ),
        migrations.CreateModel(
            name='TrabajoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('suspendido', 'Suspendido')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones_empleado', models.TextField(blank=True, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_empleados', to='cotizaciones.cotizacion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_trabajos', to='home.perfilempleado')),
                ('item_mano_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.itemmanoobra')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'unique_together': {('empleado', 'item_mano_obra')},
            },
        ),
    ]
