# Generated by Django 5.2.5 on 2025-10-03 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_remove_cliente_activo_remove_cliente_atencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_nombre_respaldo',
            field=models.CharField(blank=True, help_text='Nombre del cliente guardado como respaldo', max_length=200),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizaciones.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('finalizada', 'Finalizada')], default='borrador', max_length=20),
        ),
    ]
