# Generated by Django 5.2.5 on 2025-10-10 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_cotizacion_cliente_nombre_respaldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='comentarios_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='email_enviado_a',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_respuesta_cliente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='cotizaciones.representantecliente'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='representante_nombre_respaldo',
            field=models.CharField(blank=True, help_text='Nombre del representante guardado como respaldo', max_length=200),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='token_validacion',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('revisada', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('requiere_cambios', 'Requiere Cambios'), ('vencida', 'Vencida')], default='borrador', max_length=20),
        ),
    ]
