# Generated by Django 5.2.5 on 2025-10-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_cotizacion_comentarios_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('revisada', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('requiere_cambios', 'Requiere Cambios'), ('vencida', 'Vencida'), ('finalizada', 'Finalizada')], default='borrador', max_length=20),
        ),
    ]
