# Generated by Django 5.2.5 on 2025-11-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_alter_cotizacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='dias_alerta_previa',
            field=models.IntegerField(default=7, help_text='Días antes del vencimiento para enviar notificación', verbose_name='Días de Alerta Previa'),
        ),
        migrations.AddField(
            model_name='material',
            name='dias_entre_mantenimiento',
            field=models.IntegerField(blank=True, help_text='Número de días entre cada mantenimiento', null=True, verbose_name='Días entre Mantenimiento'),
        ),
        migrations.AddField(
            model_name='material',
            name='fecha_ultimo_mantenimiento',
            field=models.DateField(blank=True, help_text='Fecha del último mantenimiento realizado', null=True, verbose_name='Fecha Último Mantenimiento'),
        ),
        migrations.AddField(
            model_name='material',
            name='requiere_mantenimiento',
            field=models.BooleanField(default=False, verbose_name='Requiere Mantenimiento'),
        ),
    ]
