# Generated by Django 5.2.5 on 2025-11-27 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_material_dias_alerta_previa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestado_a', models.CharField(max_length=200, verbose_name='Prestado a')),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Préstamo')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de Devolución')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('material', models.OneToOneField(help_text='Material prestado', on_delete=django.db.models.deletion.CASCADE, related_name='prestamo_actual', to='cotizaciones.material')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Préstamo de Material',
                'verbose_name_plural': 'Préstamos de Materiales',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
