# Generated by Django 5.2.5 on 2025-11-29 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0001_initial'),  # Cambiar por tu última migración
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_codigo', models.CharField(max_length=50)),
                ('material_nombre', models.CharField(max_length=200)),
                ('prestado_a', models.CharField(max_length=200)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha esperada de devolución')),
                ('fecha_devuelto', models.DateField(verbose_name='Fecha real de devolución')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Préstamo',
                'verbose_name_plural': 'Historial de Préstamos',
                'ordering': ['-fecha_devuelto'],
            },
        ),
    ]






