# Generated by Django 5.2.5 on 2025-12-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_prestamomaterial'),
        ('cotizaciones', '0009_historialprestamo'),
    ]

    operations = [
    ]
