# Generated by Django 5.2.5 on 2025-12-03 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0010_merge_0008_prestamomaterial_0009_historialprestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaterial',
            name='horas_uso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas de uso estimadas para materiales con mantenimiento por horas', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas de Uso'),
        ),
        migrations.AddField(
            model_name='material',
            name='horas_alerta_previa',
            field=models.IntegerField(default=10, help_text='Horas antes del vencimiento para enviar notificación', verbose_name='Horas de Alerta Previa'),
        ),
        migrations.AddField(
            model_name='material',
            name='horas_entre_mantenimiento',
            field=models.IntegerField(blank=True, help_text='Número de horas de uso entre cada mantenimiento', null=True, verbose_name='Horas entre Mantenimiento'),
        ),
        migrations.AddField(
            model_name='material',
            name='horas_uso_acumuladas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de horas de uso desde el último mantenimiento', max_digits=10, verbose_name='Horas de Uso Acumuladas'),
        ),
        migrations.AddField(
            model_name='material',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('dias', 'Por Días'), ('horas', 'Por Horas de Uso')], default='dias', help_text='Seleccione si el mantenimiento es por días o por horas de uso', max_length=10, verbose_name='Tipo de Mantenimiento'),
        ),
    ]
