# Generated by Django 5.2.5 on 2025-12-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0011_itemmaterial_horas_uso_material_horas_alerta_previa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_feedback',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se envió la solicitud de feedback', null=True, verbose_name='Fecha de Solicitud de Feedback'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se finalizó el trabajo', null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_realizacion',
            field=models.DateField(blank=True, help_text='Fecha estimada para realizar el trabajo (solo para cotizaciones aprobadas)', null=True, verbose_name='Fecha Aproximada de Realización'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_realizacion_original',
            field=models.DateField(blank=True, help_text='Guarda la fecha original para detectar cambios', null=True, verbose_name='Fecha Original de Realización'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='feedback_solicitado',
            field=models.BooleanField(default=False, help_text='Indica si ya se envió el correo de feedback al cliente', verbose_name='Feedback Solicitado'),
        ),
    ]
