# Generated by Django 5.2.5 on 2025-12-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0012_cotizacion_fecha_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
