# Generated by Django 5.2.6 on 2025-12-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0013_alter_cotizacion_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Foto de evidencia del trabajo', upload_to='evidencias_trabajos/%Y/%m/%d/')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la evidencia', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='cotizaciones.trabajoempleado')),
            ],
            options={
                'verbose_name': 'Evidencia de Trabajo',
                'verbose_name_plural': 'Evidencias de Trabajos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='GastoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiales', models.DecimalField(decimal_places=2, default=0, help_text='Costo de materiales', max_digits=10)),
                ('materiales_detalle', models.TextField(blank=True, help_text='Detalle de materiales utilizados', null=True)),
                ('transporte', models.DecimalField(decimal_places=2, default=0, help_text='Costo de transporte', max_digits=10)),
                ('transporte_detalle', models.TextField(blank=True, help_text='Detalle del transporte', null=True)),
                ('otros', models.DecimalField(decimal_places=2, default=0, help_text='Otros gastos', max_digits=10)),
                ('otros_detalle', models.TextField(blank=True, help_text='Detalle de otros gastos', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='cotizaciones.trabajoempleado')),
            ],
            options={
                'verbose_name': 'Gasto de Trabajo',
                'verbose_name_plural': 'Gastos de Trabajos',
            },
        ),
    ]
