# Generated by Django 5.2.5 on 2025-12-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0015_evidenciatrabajo_gastotrabajo_solicitudweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudweb',
            name='tipo_servicio_solicitado',
            field=models.CharField(help_text='Nombre del servicio que solicita', max_length=299, verbose_name='Servicio Solicitado'),
        ),
    ]
