# Generated by Django 5.2.5 on 2025-12-18 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0016_alter_solicitudweb_tipo_servicio_solicitado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(help_text='Nombre ingresado por el visitante', max_length=200, verbose_name='Nombre del Solicitante')),
                ('email_solicitante', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Solicitante')),
                ('telefono_solicitante', models.CharField(max_length=50, verbose_name='Teléfono del Solicitante')),
                ('tipo_servicio_solicitado', models.CharField(help_text='Nombre del servicio que solicita', max_length=299, verbose_name='Servicio Solicitado')),
                ('ubicacion_trabajo', models.TextField(help_text='Dirección o lugar donde se requiere el servicio', verbose_name='Ubicación del Trabajo')),
                ('informacion_adicional', models.TextField(blank=True, help_text='Detalles adicionales proporcionados por el cliente', null=True, verbose_name='Información Adicional')),
                ('es_servicio_personalizado', models.BooleanField(default=False, help_text='Indica si es un servicio fuera del catálogo', verbose_name='Es Servicio Personalizado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('convertida', 'Convertida a Cotización'), ('descartada', 'Descartada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_revision', models.DateTimeField(blank=True, help_text='Cuando un admin la revisa', null=True, verbose_name='Fecha de Revisión')),
                ('fecha_conversion', models.DateTimeField(blank=True, help_text='Cuando se convierte a cotización', null=True, verbose_name='Fecha de Conversión')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas del administrador (no visibles para el cliente)', null=True, verbose_name='Notas Internas')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origen')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('cotizacion_generada', models.ForeignKey(blank=True, help_text='Cotización creada a partir de esta solicitud (solo después de conversión)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='cotizaciones.cotizacion', verbose_name='Cotización Generada')),
                ('procesada_por', models.ForeignKey(blank=True, help_text='Usuario que convirtió la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Procesada Por')),
            ],
            options={
                'verbose_name': 'Solicitud Web',
                'verbose_name_plural': 'Solicitudes Web',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.DeleteModel(
            name='SolicitudWeb',
        ),
        migrations.AddIndex(
            model_name='solicitud_web',
            index=models.Index(fields=['-fecha_solicitud'], name='cotizacione_fecha_s_bf2226_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud_web',
            index=models.Index(fields=['estado'], name='cotizacione_estado_57ac05_idx'),
        ),
    ]
