# Generated by Django 5.2.5 on 2025-12-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0019_agregar_unidad_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoempleado',
            name='horas_estimadas',
            field=models.FloatField(default=0.0),
        ),
    ]
