# Generated by Django 5.2.5 on 2025-12-19 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0020_trabajoempleado_horas_estimadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajoempleado',
            name='horas_estimadas',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
