# Generated by Django 5.2.6 on 2026-03-01 05:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0022_alter_itemmanoobraempleado_horas_asignadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciatrabajo',
            name='imagen',
            field=cloudinary.models.CloudinaryField(help_text='Foto de evidencia del trabajo', max_length=255, verbose_name='image'),
        ),
    ]
